container:
  image: python:slim

task:
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: echo $PYTHON_VERSION
    populate_script: python -m pip install .
  environment:
    CC: clang 
    CXX: clang++
  install_dependencies_script: |
    bash tools/cibw_linux.sh
  build_script: |
    python -m pip install .
  test_script: |
    python -m pytest tests/