env: 
  CIRRUS_CLONE_SUBMODULES: true

linux_task:
  container:
    image: quay.io/pypa/manylinux_2_28_x86_64
  only_if: changesInclude('.cirrus.yml', '**.{h,cpp,py}') 
  env:
    CC: clang 
    CXX: clang++
    PATH: ${PATH}:/opt/python/cp310-cp310/bin
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: echo $PYTHON_VERSION
  before_script: |
    python -m pip install --upgrade pip
    python -m pip install build pytest pytest-cov pytest-benchmark
  dependencies_script: |
    bash tools/cibw_linux.sh
  build_script: |
    python -m pip install . --verbose
  test_script: |
    python -m pytest tests/ --cov=primate --benchmark-skip
  uninstall_script: |
    python -m pip uninstall primate --yes
  wheel_script: |
    python -m build
  install_script: |
    python -m pip install dist/primate*.whl
  test_post_script: |
    python -m pytest tests/ --cov=primate --benchmark-skip
    coverage report -m
  
windows_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
  only_if: changesInclude('.cirrus.yml', '**.{h,cpp,py}') 
  env: 
    PATH: ${PATH}:c:\python311
  setup_python_script: |
    choco install -y python311
  dependencies_script: |
    bash tools/cibw_windows.sh
  before_script: |
    python -m pip install --upgrade pip
    python -m pip install build pytest pytest-cov pytest-benchmark
  build_script: |
    python -m pip install . --verbose
  test_script: |
    python -m pytest tests/ --cov=primate --benchmark-skip
  uninstall_script: |
    python -m pip uninstall primate -y
  wheel_script: |
    python -m build 
  install_script: |
    python -m pip install dist/primate*.whl
  test_post_script: |
    python -m pytest tests/ --cov=primate --benchmark-skip
    coverage report -m


# image: ghcr.io/getsentry/pypi-manylinux-amd64-ci
# image: python:slim
# image: quay.io/repository/pypa/manylinux_2_28_x86_64 
# skip: "!changesInclude('.cirrus.yml', '**.{js,ts}')"