project:
  type: website
  output-dir: ../
  preview:
    port: 8085
    browser: false

metadata-files:
  - _sidebar.yml

website: 
  navbar:
    title: PRIMATE
    right: 
      - icon: github
        href: https://github.com/peekxc/primate
        aria-label: GitHub
    left:
      - file: reference/index.qmd
        text: Reference
  
  search:
    keyboard-shortcut: ['f', '/', 'k']
    location: navbar # sidebar navbar 
    type: "overlay" # textbox or overlay
    copy-button: true
  
  reader-mode: true     # reader mode collapses sidebar 
  page-navigation: true # ability to go to next / prev 
  page-footer: "Copyright 2024, Matt Piekenbrock" 

quartodoc:
  # package: primate
  package: null
  source_dir: ../../src/primate
  # sidebar: _sidebar.yml
  out_index: index.qmd
  parser: google
  style: pkgdown # pkgdown, single-page
  # dynamic: true
  sections:
    - title: Lanczos
      contents: 
        - name: lanczos
          package: lanczos
        - name: rayleigh_ritz
          package: lanczos
    - title: Integrate
      contents: 
        - name: quadrature
          package: integrate
    - title: Trace
      contents:
        - name: hutch
          package: trace
          signature_name: full
        - name: hutchpp
          package: trace
          signature_name: full
        - name: xtrace
          package: trace
          signature_name: full
    - title: Diagonal
      contents:
        - name: diag
          package: diagonal
          signature_name: full
        - name: xdiag
          package: diagonal
          signature_name: full
    - title: Operators
      contents:
        - name: MatrixFunction
          package: operators
        - name: Toeplitz
          package: operators
        - name: normalize_unit
          package: operators
    - title: Random
      contents:
        - name: isotropic
          package: random
          signature_name: full
        - name: symmetric
          package: random
        - name: haar
          package: random
        # - quadrature.spectral_density
    - title: Estimators 
      contents: 
        - name: Estimator
          package: estimators
        - name: MeanEstimator
          package: estimators
        - name: ControlVariableEstimator
          package: estimators
        - name: ConvergenceCriterion
          package: estimators
        - name: CountCriterion
          package: estimators
        - name: ToleranceCriterion
          package: estimators
        - name: ConfidenceCriterion
          package: estimators
        - name: KneeCriterion
          package: estimators
    - title: Stats
      contents: 
        - name: Covariance
          package: stats
        - name: confidence_interval
          package: stats
  sidebar:
    file: "_sidebar.yml"
    search: true
    style: floating
    border: false
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Overview
      - href: table.qmd
        text: Table of matrix functions
      - text: Comparison to *imate*
        href: imate_compare.qmd
      - section: Basics 
        contents:
          - text: Installing
            href: basic/install.qmd
          - text: Integration
            href: basic/integration.qmd  
          - text: Quickstart
            href: basic/quickstart.qmd
      - section: Guides 
        contents:
          - text: Introduction
            href: guides/intro_trace.qmd
          - text: Matrix functions
            href: guides/matrix_functions.qmd  
      - section: "API Reference"
        contents:
          - "{{ contents }}"
filters:
  - pseudocode  

format:
  html:
    include-in-header: 
      - bokeh_cdn.html
    theme: 
      light: flatly
      dark: darkly
    css: custom.css
    toc: true
    margin-left: 0em
    html-math-method: katex
    # highlight-style: a11y
    # mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap


