project:
  type: website
  output-dir: ../

filters:
  - pseudocode

website:
  title: "primate"
  reader-mode: true 
  # pinned: false
  navbar: 
    title: PRIMATE
    right:
      - icon: github
        href: https://github.com/peekxc/primate
        aria-label: GitHub
  search:
    location: sidebar
    type: "overlay" # or textbox
    copy-button: true
  sidebar:
    collapse-level: 3
    search: true
    style: "floating" # or docked
    border: false # maybe true for docked
    contents:
      - href: index.qmd
        text: Overview
      # - text: "Basics"
      - href: install.qmd
        text: Installation
      - href: imate_compare.qmd
        text: Comparison to *imate*
      # - text: "Advanced"
      - section: Integration Guide
        contents:
          - href: integration/python_integration.qmd
            text: Usage from Python
          - href: integration/cpp_integration.qmd
            text: Usage from C++
          - href: integration/pybind11_integration.qmd
            text: Integrating with pybind11
      - section: User Guide 
        contents: 
          - href: guide/lanczos.qmd 
            text: The Lanczos method 
          - href: guide/slq_guide.qmd
            text: The SLQ method 
      # - text: "Reference"
      - section: API Reference 
        href: reference/index.qmd
        contents:
          - contents: 
            - href: reference/diagonalize.lanczos.qmd
              text: Lanczos
            section: Diagonalize 
          - contents: 
            - href: reference/primate.trace.sl_trace.qmd
              text: SL Trace
            - href: reference/primate.trace.sl_gauss.qmd
              text: SL Gauss 
            section: Trace 
            href: reference/trace.qmd
          - contents:
            - href: reference/random.rademacher.qmd
              text: Rademacher
            - href: reference/random.normal.qmd
              text: Normal
            section: Random 
          
# metadata-files:
#   - _sidebar.yml

quartodoc: 
  package: primate
  dir: reference
  out_index: index.qmd
  # sidebar: _sidebar.yml 
  style: pkgdown # pkgdown,single-page
  sections:
    - title: Trace
      desc: "Functions for estimating the trace of matrices and matrix functions."
      contents:
        - name: trace 
          children: separate
          members: ["sl_trace", "sl_gauss"]
    - title: Random
      desc: "Randomized module"
      contents:
        - random.rademacher
        - random.normal
    - title: Diagonalize
      desc: Diagonalization methods
      contents: 
        - diagonalize.lanczos
    - title: Misc
      desc: Miscellenous functions
      contents: 
        - get_include

  # renderer:
  #   style: CustomRenderer.py

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    margin-left: 0em
    html-math-method: katex
    # highlight-style: a11y
    # mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    include-in-header:
      text: |
        <script>
        MathJax = {
          loader: {
            load: ['[tex]/boldsymbol']
          },
          tex: {
            tags: "all",
            inlineMath: [['$','$'], ['\\(','\\)']],
            displayMath: [['$$','$$'], ['\\[','\\]']],
            processEscapes: true,
            processEnvironments: true,
            packages: {
              '[+]': ['boldsymbol']
            }
          }
        };
        </script>
        <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>


