project:
  type: website
  output-dir: ../

filters:
  - pseudocode

website:
  title: "primate"
  reader-mode: true     # reader mode collapses sidebar 
  page-navigation: true # ability to go to next / prev 
  page-footer: "Copyright 2023, Matt Piekenbrock" 
  navbar: 
    title: PRIMATE
    right:
      - icon: github
        href: https://github.com/peekxc/primate
        aria-label: GitHub
  search:
    location: navbar # sidebar navbar 
    type: "overlay" # textbox or overlay
    copy-button: true
  sidebar:
    collapse-level: 2
    style: "floating"   # or docked
    border: false       # maybe true for docked
    contents:
      - href: index.qmd
        text: Overview
      - section: Basics 
        contents:
          - text: Installation
            href: basic/install.qmd
          - text: Integration
            href: basic/integration.qmd
          # - text: Basic usage 
          #   href: basic/usage.qmd
          - text: Comparison to *imate*
            href: imate_compare.qmd
      # - text: Advanced
      - section: Theory
        contents:
          - text: Introduction 
            href: theory/intro.qmd
          - text: Matrix functions
            href: theory/matrix_functions.qmd
          - text: The Lanczos Method
            href: theory/lanczos.qmd
      - section: Advanced
        contents:
          - href: advanced/cpp_integration.qmd
            text: Usage from C++
          - href: advanced/pybind11_integration.qmd
            text: Integrating with pybind11
          - href: advanced/slq_param.qmd
            text: Parameterizing SLQ 
      # - section: User Guide 
      #   contents: 
      #     - href: guide/lanczos.qmd 
      #       text: The Lanczos method 
      #     - href: guide/slq_guide.qmd
      #       text: The SLQ method 
      # - text: "Reference"
      - section: API Reference 
        href: reference/index.qmd
        contents:
          - href: reference/diagonalize.lanczos.qmd
            text: Lanczos
          - href: reference/trace.hutch.qmd
            text: Hutch
          - href: reference/trace.xtrace.qmd
            text: XTrace
          - href: reference/operator.matrix_function.qmd
            text: Matrix Function
          # - href: reference/primate.trace.sl_gauss.qmd
          - contents:
            - href: reference/random.rademacher.qmd
              text: Rademacher
            - href: reference/random.normal.qmd
              text: Normal
            section: Random 
          
# metadata-files:
#   - _sidebar.yml

quartodoc: 
  package: primate
  dir: reference
  out_index: index.qmd
  # sidebar: _sidebar.yml 
  style: pkgdown # pkgdown,single-page
  sections:
    - title: Trace
      desc: "Functions for estimating the trace of matrices and matrix functions."
      contents:
        - trace.hutch
        - trace.xtrace
    - title: Operators
      desc: "Matrix operators"
      contents:
        - operator.matrix_function
    - title: Random
      desc: "Randomized module"
      contents:
        - random.rademacher
        - random.normal
    - title: Diagonalize
      desc: Diagonalization methods
      contents: 
        - diagonalize.lanczos
    - title: Misc
      desc: Miscellenous functions
      contents: 
        - get_include

  # renderer:
  #   style: CustomRenderer.py

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    margin-left: 0em
    html-math-method: katex
    # highlight-style: a11y
    # mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap


