version: '3'
services:
  # See for a better description of these images: https://github.com/pypa/manylinux
  manylinux28: 
    image: quay.io/pypa/manylinux_2_28_x86_64 # quay.io/pypa/manylinux_2_28_x86_64
    volumes:
      - ..:/workspace # Mount the parent folder to workspace
    command: sleep infinity
  manylinux14: 
    image: quay.io/pypa/manylinux2014_x86_64 # quay.io/pypa/manylinux_2_28_x86_64
    volumes:
      - ..:/workspace # Mount the parent folder to workspace
    command: sleep infinity
  musllinux:
    image: quay.io/pypa/musllinux_1_1_x86_64
    volumes:
      - ..:/workspace # Mount the parent folder to workspace
    command: sleep infinity
  # windows: 
  #   image: mcr.microsoft.com/windows/servercore:1903
  #   volumes:
  #     - ..:/workspace # Mount the parent folder to workspace
  #   command: sleep infinity