/* Generated by Cython 3.0.1 */

#ifndef __PYX_HAVE__primate___lapack
#define __PYX_HAVE__primate___lapack

#include "Python.h"

#ifndef __PYX_HAVE_API__primate___lapack

#ifdef CYTHON_EXTERN_C
    #undef __PYX_EXTERN_C
    #define __PYX_EXTERN_C CYTHON_EXTERN_C
#elif defined(__PYX_EXTERN_C)
    #ifdef _MSC_VER
    #pragma message ("Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.")
    #else
    #warning Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.
    #endif
#else
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C void lapack_sstev(char *, int *, float *, float *, float *, int *, float *, int *);
__PYX_EXTERN_C void lapack_dstev(char *, int *, double *, double *, double *, int *, double *, int *);
__PYX_EXTERN_C void lapack_sbdsdc(char *, char *, int *, float *, float *, float *, int *, float *, int *, float *, int *, float *, int *, int *);
__PYX_EXTERN_C void lapack_dbdsdc(char *, char *, int *, double *, double *, double *, int *, double *, int *, double *, int *, double *, int *, int *);

#endif /* !__PYX_HAVE_API__primate___lapack */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC init_lapack(void);
#else
/* WARNING: Use PyImport_AppendInittab("_lapack", PyInit__lapack) instead of calling PyInit__lapack directly from Python 3.5 */
PyMODINIT_FUNC PyInit__lapack(void);

#if PY_VERSION_HEX >= 0x03050000 && (defined(__GNUC__) || defined(__clang__) || defined(_MSC_VER) || (defined(__cplusplus) && __cplusplus >= 201402L))
#if defined(__cplusplus) && __cplusplus >= 201402L
[[deprecated("Use PyImport_AppendInittab(\"_lapack\", PyInit__lapack) instead of calling PyInit__lapack directly.")]] inline
#elif defined(__GNUC__) || defined(__clang__)
__attribute__ ((__deprecated__("Use PyImport_AppendInittab(\"_lapack\", PyInit__lapack) instead of calling PyInit__lapack directly."), __unused__)) __inline__
#elif defined(_MSC_VER)
__declspec(deprecated("Use PyImport_AppendInittab(\"_lapack\", PyInit__lapack) instead of calling PyInit__lapack directly.")) __inline
#endif
static PyObject* __PYX_WARN_IF_PyInit__lapack_INIT_CALLED(PyObject* res) {
  return res;
}
#define PyInit__lapack() __PYX_WARN_IF_PyInit__lapack_INIT_CALLED(PyInit__lapack())
#endif
#endif

#endif /* !__PYX_HAVE__primate___lapack */
