# trace.slq { #primate.trace.slq }

`trace.slq(A, matrix_function='identity', parameters=None, min_num_samples=150, max_num_samples=250, error_atol=None, error_rtol=0.01, confidence_level=0.95, outlier_significance_level=0.001, distribution='rademacher', rng_engine='pcg', seed=-1, lanczos_degree=20, lanczos_tol=None, orthogonalize=0, num_threads=0, verbose=False, plot=False, return_info=False, **kwargs)`

Estimates the trace of a matrix function $f(A)$ using stochastic Lanczos quadrature (SLQ). 

## Parameters

| Name                         | Type                                      | Description                                                                                    | Default         |
|------------------------------|-------------------------------------------|------------------------------------------------------------------------------------------------|-----------------|
| `A`                          | ndarray, sparse matrix, or LinearOperator | real, square, symmetric operator given as a ndarray, a sparse matrix, or a LinearOperator.     | _required_      |
| `matrix_function`            | str or Callable                           | float-valued function defined on the spectrum of A.                                            | `"identity"`    |
| `parameters`                 | Iterable                                  | translates 't' for the affine operator A + t*B (see details).                                  | `= None`        |
| `min_num_samples`            | int                                       | Minimum number of random vectors to sample for the trace estimate.                             | `= 10`          |
| `max_num_samples`            | int                                       | Maximum number of random vectors to sample for the trace estimate.                             | `= 50`          |
| `error_atol`                 | float                                     | Absolute tolerance governing convergence.                                                      | `= None`        |
| `error_rtol`                 | float                                     | Relative tolerance governing convergence.                                                      | `= 1e-2`        |
| `confidence_level`           | float                                     | Confidence level before converging.                                                            | `= 0.95`        |
| `outlier_significance_level` | float                                     | Outliers to ignore in trace estimation.                                                        | `0.001`         |
| `distribution`               | str                                       | zero-centered distribution to sample random vectors from.                                      | ` 'rademacher'` |
| `rng_engine`                 | str                                       | Random number engine to use.                                                                   | `= "pcg"`       |
| `seed`                       | int                                       | Seed to initialize the entropy source. Use non-negative integers for reproducibility.          | `= -1`          |
| `lanczos_degree`             | int                                       | Degree of the quadrature approximation.                                                        | `20`            |
| `lanczos_tol`                | int                                       | Acceptable residual tolerance to prematurely stop the lanczos iteration.                       | `= None`        |
| `orthogonalize`              | int                                       | Number of lanczos vectors to orthogonalize the Krylov basis.                                   | `0`             |
| `num_threads`                | int                                       | Number of threads to use in the trace estimates.                                               | `0`             |
| `plot`                       | bool                                      | If true, plots the samples of the trace estimate along with their convergence characteristics. | `= False`       |
| `return_info`                | bool                                      | whether to return a dictionary containing all the relevent details of the computation.         | `= False`       |
| `**kwargs`                   | (dict, optional)                          | additional key-values to parameterize the chosen 'matrix_function'.                            | `{}`            |

## Returns

| Type             | Description                                                            |
|------------------|------------------------------------------------------------------------|
| float            | Estimate of the trace of the matrix function $f(A)$.                   |
| (dict, optional) | If 'return_info = True', additional information about the computation. |

## See Also

lanczos : the lanczos algorithm. 



## Reference

  .. [1] Ubaru, S., Chen, J., & Saad, Y. (2017). Fast estimation of tr(f(A)) via stochastic Lanczos quadrature. 
  SIAM Journal on Matrix Analysis and Applications, 38(4), 1075-1099.