project:
  type: website

website:
  title: "primate"
  navbar: 
    title: PRIMATE
    right:
      - icon: github
        href: https://github.com/
        aria-label: GitHub
  sidebar:
    search: true 
    contents:
      - href: index.qmd
        text: Overview
      - href: install.qmd
        text: Installation
      - href: integration.qmd
        text: Integration
      - href: imate_compare.qmd
        text: Comparison to *imate*
      - href: reference/slq.qmd
        text: SLQ
    collapse-level: 3
    pinned: false
  search:
    location: sidebar
    type: textbox
    copy-button: true

metadata-files:
  - _sidebar.yml

quartodoc: 
  package: primate
  dir: reference
  sidebar: _sidebar.yml 
  style: single-page # pkgdown
  sections:
    - title: Trace module
      desc: ""
      contents:
        - trace
    - title: Random module
      desc: ""
      contents:
        - random.rademacher
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    margin-left: 0em
    # highlight-style: a11y
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap



