project:
  type: website

website:
  title: "primate"
  navbar: 
    title: PRIMATE
    right:
      - icon: github
        href: https://github.com/
        aria-label: GitHub
  sidebar:
    search: true 
    contents:
      - href: index.qmd
        text: Overview
      - href: install.qmd
        text: Installation
      - href: integration.qmd
        text: Integration
      - href: imate_compare.qmd
        text: Comparison to *imate*
    collapse-level: 3
    pinned: false
  search:
    location: sidebar
    type: textbox
    copy-button: true

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    margin-left: 0em
    # highlight-style: a11y
    # mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap



