project:
  type: website

website:
  title: "primate"
  navbar: 
    title: PRIMATE
    right:
      - icon: github
        href: https://github.com/
        aria-label: GitHub
  sidebar:
    search: true 
    contents:
      - href: index.qmd
        text: Overview
      - href: install.qmd
        text: Installation
      - href: integration.qmd
        text: Integration
      - href: imate_compare.qmd
        text: Comparison to *imate*
    collapse-level: 3
    pinned: false
  search:
    location: sidebar
    type: textbox
    copy-button: true

metadata-files:
  - _sidebar.yml

quartodoc: 
  package: primate
  title: API Reference    # API only 
  dir: _site/reference    # API only 
  style: pkgdown          # API only
  sidebar: _sidebar.yml 
  
  # renderer: 
  #   # style: _renderer.py
  #   show_signature: true
  #   show_signature_annotations: true
  #   display_name: name 
  
  # ## NOTE: THIS IS NOT THE SIDEBAR 
  # sections: 
  #   - title: Simplex Tree 
  #     contents: 
  #       - SimplexTree
  #   - title: Union Find
  #     contents: 
  #       - UnionFind

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    margin-left: 0em
    # highlight-style: a11y
    # mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap



